/*
 * Copyright (c) 2024 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://docs.edgeimpulse.com/page/terms-of-service) or Enterprise Terms of
 * Service (https://docs.edgeimpulse.com/page/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes[] = { 0, 6, 12 };

// (before - mean) / scale
const float ei_classifier_anom_scale[3] = { 1256.530117939665, 1411.2798927888255, 1787.1963901707568 };
const float ei_classifier_anom_mean[3] = { 1531.2999661673327, 1893.6619244749102, 3750.670690946827 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters[32] = {
	{ ( float[3] ) { -0.4279964864253998, 1.148612141609192, 1.1480515003204346 }, 0.10882598325095033 },
	{ ( float[3] ) { 0.2566985487937927, 0.9168856739997864, 1.6261621713638306 }, 0.13218725129439096 },
	{ ( float[3] ) { -0.23873957991600037, 1.0494818687438965, 1.222405195236206 }, 0.16017137072645338 },
	{ ( float[3] ) { -1.131894826889038, -1.2864930629730225, -0.7071586847305298 }, 0.02248081812499678 },
	{ ( float[3] ) { -0.09434067457914352, 1.045118808746338, 1.4408327341079712 }, 0.1485622772183126 },
	{ ( float[3] ) { 1.4467641115188599, -0.03420780971646309, -0.7006314992904663 }, 0.10993884827400689 },
	{ ( float[3] ) { 1.352480411529541, 0.39959093928337097, -0.6935441493988037 }, 0.14167364138930266 },
	{ ( float[3] ) { -0.3893442749977112, 1.2112724781036377, 1.6839128732681274 }, 0.1238974077416527 },
	{ ( float[3] ) { 1.3635979890823364, 0.2156059294939041, -0.6970398426055908 }, 0.10717229082445619 },
	{ ( float[3] ) { -0.4981609284877777, 1.4843302965164185, 1.9797229766845703 }, 0.18645264826528027 },
	{ ( float[3] ) { 1.2878762483596802, 0.05435857176780701, -0.6991549134254456 }, 0.11101794642746683 },
	{ ( float[3] ) { 1.2467920780181885, -0.0930178090929985, -0.6998854279518127 }, 0.09728798522822558 },
	{ ( float[3] ) { 0.9943704605102539, 0.12997709214687347, -0.69654381275177 }, 0.12764171497091303 },
	{ ( float[3] ) { 1.202083706855774, 0.23112449049949646, -0.6952643990516663 }, 0.09980608762244489 },
	{ ( float[3] ) { 1.0446484088897705, 0.3267323672771454, -0.6825472712516785 }, 0.11146926124913528 },
	{ ( float[3] ) { -0.11628793179988861, 1.1918851137161255, 1.3130345344543457 }, 0.12912920461933816 },
	{ ( float[3] ) { -0.2728801667690277, 1.2262322902679443, 1.3749035596847534 }, 0.1797989896815937 },
	{ ( float[3] ) { 0.14704632759094238, 1.1725102663040161, 1.5378904342651367 }, 0.12507831660309357 },
	{ ( float[3] ) { 1.1000287532806396, -0.004054637625813484, -0.6978085041046143 }, 0.11365505849421509 },
	{ ( float[3] ) { 1.590627908706665, 0.3381727635860443, -0.6988555788993835 }, 0.14482988344274345 },
	{ ( float[3] ) { 1.4852983951568604, 0.14058171212673187, -0.6979831457138062 }, 0.1584271531473243 },
	{ ( float[3] ) { -0.017778854817152023, 1.278196096420288, 1.434178113937378 }, 0.12167523129871663 },
	{ ( float[3] ) { 0.08424385637044907, 1.1013026237487793, 1.2992950677871704 }, 0.1462455213956403 },
	{ ( float[3] ) { -0.5184295773506165, 0.960659921169281, 1.0717010498046875 }, 0.051571459916582754 },
	{ ( float[3] ) { -0.5100027918815613, 1.133192777633667, 1.343722939491272 }, 0.18969142837265068 },
	{ ( float[3] ) { -0.1548897922039032, 1.3010129928588867, 1.7897781133651733 }, 0.17844744726361864 },
	{ ( float[3] ) { -0.400205135345459, 1.275935411453247, 1.2841713428497314 }, 0.1435206121338072 },
	{ ( float[3] ) { -0.0243556909263134, 0.8348645567893982, 1.1920170783996582 }, 0.09851731434244484 },
	{ ( float[3] ) { 0.1636223942041397, 0.7650508880615234, 1.5258150100708008 }, 0.09601151087936312 },
	{ ( float[3] ) { 0.33223435282707214, 1.1193840503692627, 1.3967818021774292 }, 0.09513831243571721 },
	{ ( float[3] ) { -0.11602457612752914, 1.2492640018463135, 1.6501221656799316 }, 0.17689099078886897 },
	{ ( float[3] ) { 0.33074161410331726, 0.9729234576225281, 1.8520535230636597 }, 0.10295279995084726 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
